# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from __future__ import print_function
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
from mailmerge import MailMerge
from datetime import date
import csv

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Body Mass Index")
        MainWindow.resize(799, 600)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignLeft)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(10, 0, 10, 10)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(50, 30, 351, 271))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(36, 45, 91, 41))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.name_box = QtWidgets.QLineEdit(self.groupBox)
        self.name_box.setGeometry(QtCore.QRect(140, 50, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)

        
        self.name_box.setFont(font)
        self.name_box.setText("")
        self.name_box.setClearButtonEnabled(True)
        self.name_box.setObjectName("name_box")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(36, 100, 91, 16))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        
        self.age_box = QtWidgets.QLineEdit(self.groupBox)
        self.age_box.setGeometry(QtCore.QRect(140, 90, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.age_box.setFont(font)
        self.age_box.setText("")
        self.age_box.setClearButtonEnabled(True)
        self.age_box.setObjectName("age_box")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(36, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.h_box = QtWidgets.QLineEdit(self.groupBox)
        self.h_box.setGeometry(QtCore.QRect(140, 130, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)

        
        self.h_box.setFont(font)
        self.h_box.setClearButtonEnabled(True)
        self.h_box.setObjectName("h_box")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(36, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        
        self.w_box = QtWidgets.QLineEdit(self.groupBox)
        self.w_box.setGeometry(QtCore.QRect(140, 170, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w_box.setFont(font)
        self.w_box.setClearButtonEnabled(True)
        self.w_box.setObjectName("w_box")

        
        self.calculate_btn = QtWidgets.QPushButton(self.groupBox)
        self.calculate_btn.setGeometry(QtCore.QRect(30, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.calculate_btn.setFont(font)
        self.calculate_btn.setStyleSheet("background-color: rgb(227, 2, 2);\n"
"color: rgb(255, 255, 255);")
        self.calculate_btn.setCheckable(False)
        self.calculate_btn.setAutoDefault(False)
        self.calculate_btn.setDefault(False)
        self.calculate_btn.setFlat(False)
        self.calculate_btn.setObjectName("calculate_btn")
        self.calculate_btn.clicked.connect(self.calculate_click)
        
        self.generate_btn = QtWidgets.QPushButton(self.groupBox)
        self.generate_btn.setGeometry(QtCore.QRect(180, 210, 131, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.generate_btn.setFont(font)
        self.generate_btn.setStyleSheet("background-color: rgb(0, 213, 14);\n"
"color: rgb(255, 255, 255);")
        self.generate_btn.setObjectName("generate_btn")
        self.generate_btn.clicked.connect(self.generate_click)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(50, 330, 111, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        
        self.livedata_text = QtWidgets.QLabel(self.tab)
        self.livedata_text.setGeometry(QtCore.QRect(50, 360, 450, 40))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.livedata_text.setFont(font)
        self.livedata_text.setObjectName("livedata_text")
        self.widget = AnalogGaugeWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(410, 40, 331, 261))
        self.widget.setObjectName("widget")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        
        self.record_table = QtWidgets.QTableWidget(self.tab_2)
        self.record_table.setGeometry(QtCore.QRect(20, 30, 711, 381))
        self.record_table.setObjectName("record_table")

        
        self.refresh_btn = QtWidgets.QPushButton(self.tab_2)
        self.refresh_btn.setGeometry(QtCore.QRect(20, 430, 171, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.refresh_btn.setFont(font)
        self.refresh_btn.setStyleSheet("background-color: rgb(4, 223, 0);\n"
"color: rgb(255, 255, 255);")
        self.refresh_btn.setObjectName("refresh_btn")
        self.refresh_btn.clicked.connect(self.loadCSVData)
        
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def loadCSVData(self):
        try:
            with open('record.csv', 'r') as file:
                csvreader = csv.reader(file)
                data = list(csvreader)

                self.record_table.setRowCount(len(data))
                self.record_table.setColumnCount(len(data[0]))

            for row_num, row_data in enumerate(data):
                for col_num, cell_data in enumerate(row_data):
                    item = QTableWidgetItem(cell_data)
                    self.record_table.setItem(row_num, col_num, item)
        except Exception as e:
            print("Error loading CSV data:", str(e))


    def generate_click(self):
        
        template = "template_bmi.docx"
        document = MailMerge(template)
        
        n = self.name_box.text()
        a = self.age_box.text()
        h = self.h_box.text()
        w = self.w_box.text()
        
        Bmi = round((float(w)/float(h)**2),2)
        print(n,a,h,w,Bmi)
        ''' {'bmi','weight','age',
            'name','height','remark'}'''
    
        
        with open('record.csv','a',newline='') as File:
            writer = csv.writer(File)
            writer.writerow([n,a,h,w,str(Bmi)])
        File.close()
        if Bmi >= 18.5 and Bmi < 25:
            document.merge(bmi=str(Bmi),
                       weight=w,
                       age=a,
                       name=n,
                       height=h,
                       remark="As per that you are normal weight")
        elif Bmi >= 25 and Bmi < 30:
            document.merge(bmi=str(Bmi),
                       weight=w,
                       age=a,
                       name=n,
                       height=h,
                       remark="As per that you are slightly overweight")
        elif Bmi >= 30 and Bmi < 40:
            document.merge(bmi=str(Bmi),
                       weight=w,
                       age=a,
                       name=n,
                       height=h,
                       remark="As per that you are Obese")
        elif Bmi >= 40 and Bmi < 60:
            document.merge(bmi=str(Bmi),
                       weight=w,
                       age=a,
                       name=n,
                       height=h,
                       remark="As per that you are Morbidly Obese")
        
        #document.write(f'{name+" "+bmi}.docx')
        document.write(f'{n}.docx')
        
        print("Success!!")
        
    def calculate_click(self):

        h = self.h_box.text()
        w = self.w_box.text()
        bmi = round((float(w)/float(h)**2),2)
        print("BMI" ,bmi)
        self.widget.updateValue(bmi)
        
        if bmi >= 18.5 and bmi < 25:
            self.livedata_text.setText(f"Your BMI : {str(bmi)} \nAs per that you are normal weight")
        elif bmi >= 25 and bmi < 30:
            self.livedata_text.setText(f"Your BMI : {str(bmi)} \nAs per that you are slightly overweight")
        elif bmi >= 30 and bmi < 40:
            self.livedata_text.setText(f"Your BMI : {str(bmi)} \nAs per that you are Obese")
        elif bmi >= 40 and bmi < 60:
            self.livedata_text.setText(f"Your BMI : {str(bmi)} \nAs per that you are Morbidly Obese")
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "BMI Calculator & Report Generator"))
        self.groupBox.setTitle(_translate("MainWindow", "Entry Detail"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Age/Sex"))
        self.label_5.setText(_translate("MainWindow", "Height(Mts)"))
        self.label_6.setText(_translate("MainWindow", "Weight(Kg)"))
        self.calculate_btn.setText(_translate("MainWindow", "Calculate"))
        self.generate_btn.setText(_translate("MainWindow", "Generate"))
        self.label_7.setText(_translate("MainWindow", "Report :"))
        self.livedata_text.setText(_translate("MainWindow", "No  Live Data Uploaded"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main"))
        self.refresh_btn.setText(_translate("MainWindow", "Refresh Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Records"))
        self.label.setText(_translate("MainWindow", "Version: 1.0.0 | Developer: Anshul Wycliffe | Free To Use Under Apache License Agreement 2023-2024**"))
from analoggaugewidget import AnalogGaugeWidget
